# Generated by Django 4.2.6 on 2023-12-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_request_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='session',
            name='to_date',
        ),
        migrations.AddField(
            model_name='session',
            name='from_time',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='to_time',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
